services:
  nextjs:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
