services:
  nextjs:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - '443:443'